// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdU8_q2B0g2vcKiZUiyMrlj8MsUsNbEIk',
    appId: '1:447891371186:web:6b8cd294746e55af3245ab',
    messagingSenderId: '447891371186',
    projectId: 'projectswe250',
    authDomain: 'projectswe250.firebaseapp.com',
    storageBucket: 'projectswe250.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTcE86it5gYpTXvjIoRtmvc5UNGhMeT8',
    appId: '1:447891371186:android:f5dea054321ee4fc3245ab',
    messagingSenderId: '447891371186',
    projectId: 'projectswe250',
    storageBucket: 'projectswe250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIuIDBMXlSEXf0dcsCy3DvhzosIpbI-bc',
    appId: '1:447891371186:ios:ab9ac2184fce9f4d3245ab',
    messagingSenderId: '447891371186',
    projectId: 'projectswe250',
    storageBucket: 'projectswe250.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIuIDBMXlSEXf0dcsCy3DvhzosIpbI-bc',
    appId: '1:447891371186:ios:ab9ac2184fce9f4d3245ab',
    messagingSenderId: '447891371186',
    projectId: 'projectswe250',
    storageBucket: 'projectswe250.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdU8_q2B0g2vcKiZUiyMrlj8MsUsNbEIk',
    appId: '1:447891371186:web:88d7576f637c883c3245ab',
    messagingSenderId: '447891371186',
    projectId: 'projectswe250',
    authDomain: 'projectswe250.firebaseapp.com',
    storageBucket: 'projectswe250.firebasestorage.app',
  );

}